# Generated by Django 2.0.6 on 2018-07-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50)),
                ('host_id', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=30)),
                ('borough', models.CharField(default='', max_length=30)),
                ('neighborhood', models.CharField(max_length=100)),
                ('reviews', models.CharField(blank=True, max_length=50)),
                ('overall_satisfaction', models.CharField(blank=True, max_length=50)),
                ('accommodates', models.CharField(blank=True, max_length=50)),
                ('bedrooms', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('minstay', models.CharField(blank=True, max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('last_modified', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
