# Generated by Django 2.0.6 on 2018-07-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbatos', '0003_auto_20180707_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvexport',
            name='host_id',
            field=models.IntegerField(),
        ),
    ]
