# Generated by Django 2.0.6 on 2018-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbatos', '0004_auto_20180707_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvexport',
            name='room_id',
            field=models.IntegerField(),
        ),
    ]
