# Generated by Django 2.0.6 on 2018-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbatos', '0006_auto_20180707_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvexport',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
