# Generated by Django 2.0.6 on 2018-07-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbatos', '0007_auto_20180707_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvexport',
            name='bedrooms',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='csvexport',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4),
        ),
    ]
