# Generated by Django 2.0.6 on 2018-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbatos', '0008_auto_20180707_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvexport',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
