# Generated by Django 2.0.6 on 2018-07-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbatos', '0009_auto_20180707_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvexport',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
